// automatically generated by the FlatBuffers compiler, do not modify

package com.bzsoft.rocko.model.fbdata;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FBData extends Table {
  public static FBData getRootAsFBData(ByteBuffer _bb) { return getRootAsFBData(_bb, new FBData()); }
  public static FBData getRootAsFBData(ByteBuffer _bb, FBData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean FBDataBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "BDAT"); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public FBData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FBDataInfo info(int j) { return info(new FBDataInfo(), j); }
  public FBDataInfo info(FBDataInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int infoLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createFBData(FlatBufferBuilder builder,
      int infoOffset) {
    builder.startObject(1);
    FBData.addInfo(builder, infoOffset);
    return FBData.endFBData(builder);
  }

  public static void startFBData(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addInfo(FlatBufferBuilder builder, int infoOffset) { builder.addOffset(0, infoOffset, 0); }
  public static int createInfoVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startInfoVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFBData(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFBDataBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "BDAT"); }
  public static void finishSizePrefixedFBDataBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "BDAT"); }
}

