// automatically generated by the FlatBuffers compiler, do not modify

package com.bzsoft.rocko.model.fbdata;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FBDataInfo extends Table {
  public static FBDataInfo getRootAsFBDataInfo(ByteBuffer _bb) { return getRootAsFBDataInfo(_bb, new FBDataInfo()); }
  public static FBDataInfo getRootAsFBDataInfo(ByteBuffer _bb, FBDataInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public FBDataInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short reason() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public int includedLocations(int j) { int o = __offset(6); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int includedLocationsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer includedLocationsAsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer includedLocationsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }
  public int excludedLocations(int j) { int o = __offset(8); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int excludedLocationsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer excludedLocationsAsByteBuffer() { return __vector_as_bytebuffer(8, 4); }
  public ByteBuffer excludedLocationsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 4); }

  public static int createFBDataInfo(FlatBufferBuilder builder,
      short reason,
      int includedLocationsOffset,
      int excludedLocationsOffset) {
    builder.startObject(3);
    FBDataInfo.addExcludedLocations(builder, excludedLocationsOffset);
    FBDataInfo.addIncludedLocations(builder, includedLocationsOffset);
    FBDataInfo.addReason(builder, reason);
    return FBDataInfo.endFBDataInfo(builder);
  }

  public static void startFBDataInfo(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addReason(FlatBufferBuilder builder, short reason) { builder.addShort(0, reason, 0); }
  public static void addIncludedLocations(FlatBufferBuilder builder, int includedLocationsOffset) { builder.addOffset(1, includedLocationsOffset, 0); }
  public static int createIncludedLocationsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startIncludedLocationsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addExcludedLocations(FlatBufferBuilder builder, int excludedLocationsOffset) { builder.addOffset(2, excludedLocationsOffset, 0); }
  public static int createExcludedLocationsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startExcludedLocationsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFBDataInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

